server:
  host: #"0.0.0.0"
  port: 8080

auth_postgres:
  host: "shared-postgres"
  port: 5432
  user:
  password:
  db:
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime: "1h"

redis:
  host:
  port:
  password:
  db: 0

jwt:
  secret_key:
  access_duration: "15m"
  refresh_duration: "2160h"
